### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by rudvfaden** [DeborahK/Angular-Routing#24]
I cannot find the api/products  folder anywhere in the app?

**Comment by DeborahK** [comment]
There is no api/products folder required for this project.

Because the routing includes an edit operation, the HTTP calls couldn't use a JSON file. (You can use a JSON file to read data, but not write data.)

So this course uses the `angular-in-memory-web-api` library provided by the Angular team specifically for "mocking" HTTP requests. See the product-data.ts file for the data used by the application.

**Comment by rudvfaden** [comment]
Sorry. My bad. Somehow it did no work on my work computer. Switching to my mac somehow it worked.
